calculator application/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using calculator_application.Models;
using calculator_application.Service.StatisticalCalculator;

namespace calculator_application.Controllers
{
    public class CalculatorController : Controller
    {
        private readonly string _cacheKey = "CacheKey";
        private IStatisticalCalculator _statisticalCalculator;
        public CalculatorController()
        {
         _statisticalCalculator = new StatisticalCalculator();   
        }
        // GET: Calculator
        public ActionResult Index()
        {
            HttpContext.Cache.Insert(_cacheKey, new List<Operation>());

            return View();
        }

        [HttpPost]
        public ActionResult Calculate(double number, string add, string clear)
        {
            var operations = HttpContext.Cache.Get(_cacheKey) as List<Operation> ?? new List<Operation>();

            if (!string.IsNullOrEmpty(add))
            {
                _statisticalCalculator.AddNumbers(number, ref operations);

                HttpContext.Cache.Insert(_cacheKey, operations);
            }
            if (!string.IsNullOrEmpty(clear))
            {
                _statisticalCalculator.ClearNumbers(ref operations);

                HttpContext.Cache.Insert(_cacheKey, operations);
            }

            return View(operations);

        }
    }
}

calculator application/Views/Calculator/Calculate.cshtml
@using calculator_application.Models
@model System.Collections.Generic.List<calculator_application.Models.Operation>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Calculate", "Calculator", FormMethod.Post, Model))
        {

            <input type="text" style="width: 300px" name="number" />
            <input type="submit" value="add" name="add" />
            <input type="submit" value="clear" name="clear" />


        }
        @if (Model != null)
        {
            <ul>
                @foreach (var operation in Model.ToList())
                {
                    <li>
                        @operation.Number
                    </li>
                }
            </ul>
        }
    </div>

</body>
</html>

calculator application/Views/Calculator/Index.cshtml
@using calculator_application.Models
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
    <script>
        
    </script>
</head>

<body>
    <div>
        @using (Html.BeginForm("Calculate", "Calculator", FormMethod.Post))
        {

            <input type="text" style="width: 300px" name="number" />
            <input type="submit" value="add" name="add" />
            <input type="submit" value="clear" name="clear"/>

            
        }
        
    </div>

</body>
</html>